---
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gems"
    labels: ["dependabot"]
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
