#! /bin/sh
### BEGIN INIT INFO
# Provides:          dyndnsd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Handle dyndnsd.rb gem
### END INIT INFO

# using the system ruby's gem binaries directory
DAEMON="/var/lib/gems/1.8/bin/dyndnsd"

CONFIG_FILE="/opt/dyndnsd/config.yaml"

DAEMON_OPTS="$CONFIG_FILE"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting dyndnsd.rb" "dyndnsd"
    start-stop-daemon --start --quiet --oknodo --make-pidfile --pidfile "/var/run/dyndnsd.pid" --background --exec $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping dyndnsd.rb" "dyndnsd"
    start-stop-daemon --stop --quiet --oknodo --pidfile "/var/run/dyndnsd.pid"
    log_end_msg $?
    ;;
  restart|force-reload)
    log_daemon_msg "Restarting dyndnsd.rb" "dyndnsd"
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile "/var/run/dyndsd.pid"
    start-stop-daemon --start --quiet --oknodo --make-pidfile --pidfile "/var/run/dyndnsd.pid" --background --exec $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
    ;;
  *)
    log_action_msg "Usage: $0 {start|stop|restart|force-reload}"
    exit 2
    ;;
esac
