---
name: cd

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release-dockerimage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: sleep 30

    - name: Extract dyndnsd version from tag name
      run: |
        echo "DYNDNSD_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: cmur2
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image for dyndnsd ${{ env.DYNDNSD_VERSION }}
      uses: docker/build-push-action@v2
      with:
        context: docker
        build-args: |
          DYNDNSD_VERSION=${{ env.DYNDNSD_VERSION }}
        push: true
        tags: cmur2/dyndnsd:v${{ env.DYNDNSD_VERSION }}
